/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package zohomobileinventory;
import java.util.Date;
/**
 *
 * @author User
 */
public class frmAdmin extends javax.swing.JFrame {

    /**
     * Creates new form frmAdmin
     */
    public frmAdmin() {
        initComponents();
        
        Date dtDate = new Date();
        lblDate.setText(dtDate.toString());     //DISPLAYS THE DATE
    }
    
    private void spLogout()
    {
        frmLogin frmLogin = new frmLogin();
        frmLogin.show();           //CODE THAT CALLS THE LOGIN FORM, ACTS AS EXIT OR LOGOUT.
        this.setVisible(false);
    }
    
    private void spAddAdmin()
    {
        frmAddAdmin frmAddAdmin = new frmAddAdmin();
        frmAddAdmin.show();         //CALLS THE ADD ADMIN FORM, THIS IS WHERE AN ACCOUNTANT IS ADDED.
        this.setVisible(false);
    }

    private void spViewAccountant()
    {
        frmViewAccountant frmViewAccountant = new frmViewAccountant();
        frmViewAccountant.show();           //CALLS THE VIEW ACCOUNTANT FORM, THIS IS WHERE DETAILS WILL BE VIEWED.
        this.setVisible(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnViewAccountant = new javax.swing.JButton();
        btnAddAcountant = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        lblDate = new javax.swing.JLabel();
        lblAdminTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin");
        setBackground(new java.awt.Color(255, 255, 255));

        btnViewAccountant.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnViewAccountant.setText("View Accountant");
        btnViewAccountant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewAccountantantActionPerformed(evt);
            }
        });

        btnAddAcountant.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAddAcountant.setText("Add Accountant");
        btnAddAcountant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAcountantActionPerformed(evt);
            }
        });

        btnLogout.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        lblDate.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N

        lblAdminTitle.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblAdminTitle.setText("WELCOME ADMIN");
        lblAdminTitle.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        lblAdminTitle.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnLogout)
                .addGap(41, 41, 41))
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDate, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAdminTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnViewAccountant)
                            .addComponent(btnAddAcountant))))
                .addContainerGap(149, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblAdminTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(btnAddAcountant)
                .addGap(37, 37, 37)
                .addComponent(btnViewAccountant)
                .addGap(21, 21, 21)
                .addComponent(btnLogout)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(lblDate, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
spLogout();
// TODO add your handling code here:
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnAddAcountantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAcountantActionPerformed
spAddAdmin();// TODO add your handling code here:
    }//GEN-LAST:event_btnAddAcountantActionPerformed

    private void btnViewAccountantantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewAccountantantActionPerformed
spViewAccountant();// TODO add your handling code here:
    }//GEN-LAST:event_btnViewAccountantantActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddAcountant;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnViewAccountant;
    private javax.swing.JLabel lblAdminTitle;
    private javax.swing.JLabel lblDate;
    // End of variables declaration//GEN-END:variables
}
