/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package zohomobileinventory;
import java.io.File;
import java.io.FileWriter;
import java.util.Date;
import javax.swing.JOptionPane;
/**
 *
 * @author User
 */
public class frmAddProduct extends javax.swing.JFrame {

    /**
     * Creates new form frmAddProduct
     */
    public frmAddProduct() {
        initComponents();
        
        Date dtDate = new Date();
        lblDate.setText(dtDate.toString());     //DISPLAYS THE DATE
    }
    
    private void spCreateFile()
    {
        File Storeman = new File("Product Data.txt");
   
        try
        {
            Storeman.createNewFile();       //CREATES THE PRODUCT DATA TEXT FILE.
        }
        catch(Exception EX)
        {
            JOptionPane.showMessageDialog(null, EX);   
        }    
    }

    private void spAddProduct()
    {
        String strAddProduct = txtAddProduct.getText();
        String strProductDescription = txtProductDescription.getText();
        String strQuantity = txtQuantity.getText();
    
 
        //CHECKS OF ALL REQUIRED DETAILS ARE ENTERED.
        if(strAddProduct .equals("") && strProductDescription .equals ("") && strQuantity .equals("") || strAddProduct .equals(" ") && strProductDescription .equals (" ") && strQuantity .equals(" "))
        {
            JOptionPane.showMessageDialog(null, "Please enter product details");
            txtAddProduct.setText(null);
            txtProductDescription.setText(null);
            txtQuantity.setText(null);
        }
        
        else if(strAddProduct .equals("") || strAddProduct .equals(" "))
        {
        JOptionPane.showMessageDialog(null, "Please enter a Product");
        }
    
        else if(strProductDescription .equals ("") || strProductDescription .equals (" "))                  
        {
        JOptionPane.showMessageDialog(null, "Please enter Product description");
        }
    
        else if(strQuantity .equals ("") || strQuantity .equals (" "))
        {
            JOptionPane.showMessageDialog(null, "Please enter quantity");
        }
    
    //WRITES THE ENTERED DETAILS TO THE PRODUCT DATA TEXTFILE.
        if(!strQuantity .equals("") && !strQuantity .equals(" ") && !strProductDescription .equals("") && !strProductDescription .equals(" ") && !strAddProduct .equals("") && !strAddProduct .equals(" "))
        {
        try
        {
            spCreateFile();
            String strfilename = "Product Data.txt";
            FileWriter fw = new FileWriter(strfilename, true);
            fw.write("Product Name: " + strAddProduct + " | " + "Description: " + strProductDescription +" | "+ "Quantity: " + strQuantity + "\r\n");
            fw.close();
    
            JOptionPane.showMessageDialog(null, "Information Has Been Successfully Added.");
    
            txtAddProduct.setText(null);
            txtProductDescription.setText(null);
            txtQuantity.setText(null);
        }
        catch(Exception EX)
        {
            JOptionPane.showMessageDialog(null, "Data was not added");  
        }
        }
    }
    private void spBack()
    {
        frmStoreman frmStoreman = new frmStoreman();
        frmStoreman.show();           //CALLS THE STOREMAN FORM, ACTS AS A BACK BUTTON.
        this.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDate = new javax.swing.JLabel();
        lblAddProduct = new javax.swing.JLabel();
        lblProductDescription = new javax.swing.JLabel();
        lblQuantity = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        txtAddProduct = new javax.swing.JTextField();
        txtProductDescription = new javax.swing.JTextField();
        txtQuantity = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add Product");

        lblDate.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N

        lblAddProduct.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblAddProduct.setText("Add Product:");

        lblProductDescription.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblProductDescription.setText("Product Description:");

        lblQuantity.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblQuantity.setText("Quantity:");

        btnBack.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnBack.setText("< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnSave.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(lblProductDescription)
                                        .addGap(18, 18, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblQuantity)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(174, 174, 174))
                                    .addComponent(txtProductDescription)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lblAddProduct)
                                .addGap(69, 69, 69)
                                .addComponent(txtAddProduct)))
                        .addGap(48, 48, 48))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(btnBack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSave)
                        .addGap(94, 94, 94))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDate, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddProduct)
                    .addComponent(txtAddProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProductDescription)
                    .addComponent(txtProductDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQuantity)
                    .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(btnSave))
                .addGap(42, 42, 42)
                .addComponent(lblDate, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
spBack();// TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
spAddProduct();        // TODO add your handling code here:
    }//GEN-LAST:event_btnSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmAddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmAddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmAddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmAddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmAddProduct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel lblAddProduct;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblProductDescription;
    private javax.swing.JLabel lblQuantity;
    private javax.swing.JTextField txtAddProduct;
    private javax.swing.JTextField txtProductDescription;
    private javax.swing.JTextField txtQuantity;
    // End of variables declaration//GEN-END:variables
}
