/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package zohomobileinventory;
import java.util.Date;
/**
 *
 * @author User
 */
public class frmStoreman extends javax.swing.JFrame {

    /**
     * Creates new form frmStoreman
     */
    public frmStoreman() {
        initComponents();
        
        Date dtDate = new Date();
        lblDate.setText(dtDate.toString());     //DISPLAYS THE DATE
    }

    private void spAddStoreman()
    {
        frmAddStoreman frmAddStoreman = new frmAddStoreman();
        frmAddStoreman.show();      //CALLS THE ADD STOREMAN FORM, THIS WHERE OTHER STOREMAN ARE ADDED.
        this.setVisible(false);
    }
    
    private void spViewStoreman()
    {
        frmViewStoreman frmViewStoreman = new frmViewStoreman();
        frmViewStoreman.show();     //CALLS THE VIEW STOREMAN FORM, THIS WHERE STOREMAN DETAILS ARE VIEWED.
        this.setVisible(false);
    }
    
    private void spAddProduct()       
    {
        frmAddProduct frmAddProduct = new frmAddProduct();
        frmAddProduct.show();       //CALLS THE ADD PRODUCT FORM, THIS WHERE PRODUCT INFORMATION IS ADDED TO A PRODUCT DATA TEXT FILE.
        this.setVisible(false);
    }
    
    private void spLogout()
    {
        frmLogin frmLogin = new frmLogin();
        frmLogin.show();        //CODE THAT CALLS THE LOGIN FORM, ACTS AS EXIT OR LOGOUT.
        this.setVisible(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblStoremanTitle = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        btnAddStoreman = new javax.swing.JButton();
        btnViewStoreman = new javax.swing.JButton();
        btnAddProduct = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Storeman");

        lblStoremanTitle.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblStoremanTitle.setText("WELCOME STOREMAN");
        lblStoremanTitle.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("")));

        lblDate.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N

        btnAddStoreman.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAddStoreman.setText("Add Storeman");
        btnAddStoreman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddStoremanActionPerformed(evt);
            }
        });

        btnViewStoreman.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnViewStoreman.setText("View Storeman");
        btnViewStoreman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewStoremanActionPerformed(evt);
            }
        });

        btnAddProduct.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAddProduct.setText("Add Product");
        btnAddProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddProductActionPerformed(evt);
            }
        });

        btnLogout.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblStoremanTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAddStoreman)
                            .addComponent(btnViewStoreman)
                            .addComponent(btnAddProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblDate, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(177, 177, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnLogout)
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblStoremanTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(btnAddStoreman)
                .addGap(32, 32, 32)
                .addComponent(btnViewStoreman)
                .addGap(34, 34, 34)
                .addComponent(btnAddProduct)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLogout)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(lblDate, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddStoremanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddStoremanActionPerformed
spAddStoreman();// TODO add your handling code here:
    }//GEN-LAST:event_btnAddStoremanActionPerformed

    private void btnViewStoremanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewStoremanActionPerformed
spViewStoreman();// TODO add your handling code here:
    }//GEN-LAST:event_btnViewStoremanActionPerformed

    private void btnAddProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddProductActionPerformed
spAddProduct();// TODO add your handling code here:
    }//GEN-LAST:event_btnAddProductActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
spLogout();// TODO add your handling code here:
    }//GEN-LAST:event_btnLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmStoreman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmStoreman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmStoreman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmStoreman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmStoreman().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddProduct;
    private javax.swing.JButton btnAddStoreman;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnViewStoreman;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblStoremanTitle;
    // End of variables declaration//GEN-END:variables
}
